/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package datamanager.sql;

import com.screenscraper.datamanager.sql.SqlTableSchema;
import com.screenscraper.datamanager.SchemaKey;
import java.util.HashSet;
import java.util.Arrays;
import com.screenscraper.datamanager.skeleton.BasicSchemaAttr;
import com.screenscraper.datamanager.DataObject.ObjectType;
import java.util.Map;
import java.util.Set;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author ryan
 */
public class SqlSchemaTest {

    public SqlSchemaTest() {
    }

    @BeforeClass
    public static void setUpClass() throws Exception {
    }

    @AfterClass
    public static void tearDownClass() throws Exception {
    }

    @Before
    public void setUp() {
    }

    @After
    public void tearDown() {
    }

    /**
     * Test of getAutoIncrementColumn method, of class SqlSchema.
     */
    @Test
    public void testGetAutoIncrementColumn() {
        System.out.println("getAutoIncrementColumn");
        SqlTableSchema instance = new SqlTableSchema("test");
        instance.addColumn("pk", ObjectType.Integer);
        instance.addAttr("pk", BasicSchemaAttr.autoGenerated, BasicSchemaAttr.Option.yes.name());
        Set<String> result = instance.getAutoGeneratedColumns();
        assertEquals(new HashSet(Arrays.asList("pk")), result);
    }

    /**
     * Test of getDefaultAttrs method, of class SqlSchema.
     */
    @Test
    public void testGetDefaultAttrs() {
        System.out.println("getDefaultAttrs");
        System.out.println("getAutoIncrementColumn");
        SqlTableSchema instance = new SqlTableSchema("test");
        instance.addColumn("pk", ObjectType.Integer);
        Map result = instance.getDefaultAttrs();
        System.out.println(result);
        assertFalse(result.isEmpty());
    }

    /**
     * Test of getPrimaryKeyColumns method, of class SqlSchema.
     */
    @Test
    public void testGetPrimaryKeyColumns() {

        System.out.println("getAutoIncrementColumn");
        SqlTableSchema instance = new SqlTableSchema("test");
        instance.addColumn("pk1", ObjectType.Integer);
        instance.addColumn("pk2", ObjectType.String);

        SchemaKey primary = new SchemaKey("pk", SchemaKey.Type.primary, Arrays.asList("pk1","pk2"));
        instance.setPrimaryKey(primary);
        
        Set<String> expResult = new HashSet(Arrays.asList("pk1","pk2"));
        Set<String> result = instance.getPrimaryKeyColumns();
        assertEquals(expResult, result);
    }

}