/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.screenscraper.datamanager.skeleton;
import com.screenscraper.datamanager.DataObject;
import com.screenscraper.datamanager.SchemaAttr;
import java.util.HashSet;
import java.util.Set;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
/**
 *
 * @author ryan
 */
public enum BasicSchemaAttr implements SchemaAttr{


    type("type", DataObject.ObjectType.Object, DataObject.ObjectType.values()),
    parentSchema("parentSchema", null),
    parentKey("parentKey", null),
    autoGenerated("autoGenerated", Option.no, Option.no,Option.yes),
    key("key", Option.no, Option.no, Option.yes),
    defaultValue("defaultValue", null),
    isNullable("isNullable", Option.yes,Option.no,Option.yes),
    size("size",null);

    private static Log log = LogFactory.getLog(BasicSchemaAttr.class);

    public enum Option{
        yes("yes"),no("no"),empty(""), trueVal("true"), falseVal("false");
        private String val;
        Option(String option){
            this.val=option;
        }

        public boolean isEqual(String option){
            if(val==null){
                return (option==null);
            }
            return val.equals(option);
        }

        public boolean isEqual(Enum option){
                return this.isEqual(option.toString());
        }

        @Override
        public String toString(){
            return val;
        }
    }

    private Set<String> options;
    private final String name;
    private Enum defaultOption;

    BasicSchemaAttr(String name, Enum defaultOption, Enum...option){
        this.name=name;
        options= new HashSet();
        for(Enum opt : option){
           options.add(opt.toString());
        }
        this.defaultOption=defaultOption;
    }

    public Set<String> getOptions()
    {
        Set<String> retStr = new HashSet<String>();
        for(String o: options){
            retStr.add(o.toString());
        }
        return retStr;
    }

    public String getDefaultOption(){
        return (defaultOption==null) ? null : defaultOption.name();
    }

    public static SchemaAttr fromString(String attr){
        try{
            return BasicSchemaAttr.valueOf(attr);
        }catch(IllegalArgumentException e){
           log.warn("attemping to add uknown attribute: " + attr);
        }
        return null;
    }



    @Override
    public String toString()
    {
        return name;
    }
}
